### ISSUE TITLE
custom key mappings

### ISSUE THREAD

**Issue by xunam** [felipec/notmuch-vim#15]
Hi,

I am giving a try to notmuch-vim as a mail client and so far I like how it is simple and efficient. The various options for customization are nice but I would like to add my own key mappings to folders and search buffers using vim's `nmap` and this does not seem to work. Specifically, I would like that pressing `f` in folder or search buffers calls the command for fetching new mail. I have tried adding

```
autocmd FileType notmuch-folders nmap <buffer> f :!mbsync inbox<cr>
```

in my `vimrc` but the mapping is just ignored.

After some exploration of the code, I found that the function `set_map` in `notmuch.vim` starts with `nmapclear <buffer>` so it effectively clears any custom normal-mode mappings when creating a notmuch buffer. Adding my mapping in `notmuch_custom_search_maps` does not work since the command I want is not a function provided in `notmuch.vim`.

Is there a proper way to fix this issue?

**Comment by felipec** [comment]
I've added a `system` function and a folder mapping option, so you can do:

```vim
let g:notmuch_custom_folders_maps = {
	\ 'f':		'system("mbsync inbox")',
	\ }
```
