### ISSUE TITLE
Does not load..

### ISSUE THREAD

**Issue by nachiket** [felipec/notmuch-vim#16]
I've installed notmuch-vim from Ubuntu apt-get and get a "Not an editor command: Notmuch" error. I see that notmuch.vim is loaded in vim. I tried to clone this repo and install, but same result.

**Comment by EvilPudding** [comment]
Do you have ruby enabled on your vim?

**Comment by nachiket** [comment]
Yes. I've followed all the steps on the README here https://github.com/felipec/notmuch-vim

```➜  ~ vim --version | grep +ruby
+diff            +menu            +ruby            +X11```

```➜  ~ ruby -e "require 'notmuch'"
➜  ~ ```

I installed notmuch from the git branch 0.15.2 as indicated.

Still get the same error -- 
```Error detected while processing command line:
E492: Not an editor command: :Notmuch```

**Comment by nachiket** [comment]
Ah never mind -- I was loading "Notmuch" instead of "NotMuch". Sigh!
