### ISSUE TITLE
Error at initialization

### ISSUE THREAD

**Issue by Lupjo** [felipec/notmuch-vim#20]
When launching `:NotMuch` in neovim, I get the following error, and an empty result. `notmuch` is initialized, `notmuch search tag:inbox` gives a non-empty result.

```
Error detected while processing function <SNR>41_NotMuch:                   
line  474:
ArgumentError: wrong array length at 8 (expected 2, was 1)
Error detected while processing function <SNR>41_NotMuch[478]..<SNR>41_folders[1]..<SNR>41_new_buffer:
line    6:
TypeError: no implicit conversion of nil into String
Error detected while processing function <SNR>41_NotMuch[478]..<SNR>41_folders:
line    2:
NoMethodError: undefined method `query' for nil:NilClass
```

**Comment by felipec** [comment]
No idea what could be happening here.

Please provide the versions of the following:

 * ruby
 * neovim
 * neovim-ruby
 * notmuch

**Comment by Lupjo** [comment]
- Ruby's version: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]`
- Neovim's version:  `NVIM v0.5.0`
- neovim-ruby: `0.8.1`
- notmuch: `0.32.2`

**Comment by felipec** [comment]
OK. You have the exact same versions as me.

I found the issue though: you don't have configures `search.exclude_tags`. I have the fix ready.

**Comment by lupjo** [comment]
Wow that was efficient! Thanks a lot
